### ISSUE TITLE
Helm Templating Failing for datahub-cleanup-job-template.yml

### ISSUE THREAD

**Issue by drew-vz** [acryldata/datahub-helm#325]
The Helm templating is failing for the file datahub-cleanup-job-template.yml. This is due to the resources block of the yaml being improperly indented in the yaml spec.

**To Reproduce**
Run a helm upgrade with the DataHubUpgrade job enabled, the resources (limits, requests) is not being properly indented when templated into the yaml.

`Error: UPGRADE FAILED: YAML parse error on datahub/charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml: error converting YAML to JSON: yaml: line 91: did not find expected '-' indicator
`
Commit: https://github.com/acryldata/datahub-helm/commit/1f9ffe6cc6aab62f8f2e4da2c9e3d2b3f920f349

**Expected behavior**
https://github.com/acryldata/datahub-helm/blob/1f9ffe6cc6aab62f8f2e4da2c9e3d2b3f920f349/charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml#LL74C2-L74C2 
^^This line should be `nindent 16`

**Comment by gopikaops** [comment]
we're also seeing that behavior with prerrequisites v 0.0.17 and datahub v  0.2.170

**Comment by tusharm** [comment]
hi, came across these other errors after fixing the above locally:
```
$ helm -n datahub install datahub .                                                                               
Error: INSTALLATION FAILED: template: datahub/charts/datahub-gms/templates/deployment.yaml:53:22: executing "datahub/charts/datahub-gms/templates/deployment.yaml" at <.Values.global.elasticsearch.search.custom.enabled>: nil pointer evaluating interface {}.enabled
```
and
```
$ helm -n datahub install datahub .                                                                               
Error: INSTALLATION FAILED: template: datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml:71:34: executing "datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml" at <.Values.datahubUpgrade.cleanupJob.resources>: nil pointer evaluating interface {}.resources
```
Seems these configs are missing from the `values.yaml` file?

**Comment by julio-pimentel** [comment]
This bug is not allowing to install Datahub helm chart for new users. What version could be used while this is solved?

**Comment by gopikaops** [comment]
Hi
This issue is still occurring
Could you please check?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
